#настройки сервера
server:
  port : 8189
  servlet:
    context-path: /app

#настройки JPA
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        jdbc:
          batch_size: 1000
          format_sql: true


  #База данных
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://10.182.128.188:5432/smsSender_base?currentSchema=public
    url: jdbc:postgresql://localhost:5432/smsSender_base?currentSchema=public
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
  #Загрузка файлов
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

#Logging
logging:
  level:
    jdbc:
      sqlonly: info
      resultsettable: info
      sqltiming: fatal
      audit: fatal
      resultset: fatal
      connection: fatal

#SmsAPI settings
smsApi:
  user: ${SMS_USER}
  password: ${SMS_PASSWORD}
  from : ${SMS_FROM}

#Стоимость смс
sms:
  price: 0.0145

#ФТП настройки
ftp:
  connection:
    server: ${FTP_SERVER}
    port: ${FTP_PORT}
    login: ${FTP_LOGIN}
    password: ${FTP_PASSWORD}
  baseFolder: ${FTP_BASE_FOLDER}

#Номера телефонов администраторов приложения, для высылки служебной информации(например о неверном импорте)
#Можно указывать через запятую
adminsNumbers: ${ADMINS_NUMBERS}